import board

# Audio Configuration
RATE = 16_000
CHUNK = 512  # 32 ms at 16 kHz
FFT_SIZE = 2048
TEMPO_WINDOW = 2048

# Timing Thresholds
STATE_UPDATE_SECONDS = 1.0
NO_BEAT_IDLE_SECONDS = 4.0

# Initial Behavior
INITIAL_LISTEN_MOVE = "DANCE_CHASSIS_BREATHE"
ENABLE_YAMNET = True

# LCD Display Pins
DISPLAY_CS_PIN = board.CE0
DISPLAY_DC_PIN = board.D24
DISPLAY_RST_PIN = board.D25

# LED Configuration
LED_PIN = 13
LED_CHANNEL = 1
NUM_LEDS = 7
LED_BRIGHTNESS = 100

# READY-driven choreography pools
DANCE_POOLS = {
    ("SLOW", "LOW", "SMOOTH"): ["DANCE_CHASSIS_BREATHE", "DANCE_BEG_WAVE", "DANCE_WAVE", "DANCE_PEACOCK"],
    ("SLOW", "HIGH", "BUSY"): ["DANCE_HEADBANG", "DANCE_PITCH_PIVOT", "DANCE_PEACOCK", "DANCE_RIPPLE"],
    ("FAST", "LOW", "SMOOTH"): ["DANCE_TWIST", "DANCE_CIRCLE", "DANCE_RIPPLE", "DANCE_WAVE"],
    ("FAST", "HIGH", "SMOOTH"): ["DANCE_CIRCLE", "DANCE_SALSA", "DANCE_ROLL_FAST", "DANCE_PITCH_PIVOT"],
    ("FAST", "HIGH", "BUSY"): ["DANCE_GALLOP", "DANCE_TWITCH", "DANCE_STROBE", "DANCE_PULSE", "DANCE_WORM"],
}

SAFE_DANCES = ["DANCE_TWIST", "DANCE_RIPPLE", "DANCE_CIRCLE", "DANCE_WAVE", "DANCE_PITCH_PIVOT"]
